# Generated by Django 4.1.1 on 2022-11-29 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(verbose_name='added_at')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_text', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(verbose_name='added_at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated_at')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
