# Generated by Django 4.1.1 on 2022-10-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="command",
            old_name="command",
            new_name="creator",
        ),
    ]
