# Generated by Django 4.1.1 on 2022-10-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_command_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="updated_at",
            field=models.DateTimeField(null=True, verbose_name="updated_at"),
        ),
    ]
